#!/bin/bash

wget https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz
tar -xvzf openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz
mv openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit/oc /usr/bin
rm -rf openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit
